// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rljepbhkwlavekzgdpaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsamVwYmhrd2xhdmVremdkcGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Mzg2MDIsImV4cCI6MjA2OTAxNDYwMn0.1uOtG7nsaKQB_sdhM-zVbdYXiRlwG5C5NXvvmbZlXnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});